Pandas-DataFrame And Series 

Pandas is a powerful data manipulation library in python, widely used for data analysis and data cleaning.It provides two primary data structures: series and dataframe. A series is a one dimensional array like object, while a dataframe is a two dimensional ,size-mutable, and potentially hetrogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\himanshu sharma\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\himanshu sharma\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\himanshu sharma\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\himanshu sharma\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\himanshu sharma\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\himanshu sharma\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [4]:
#series
## A pandas series is a one dimensional array like onject  that can hold any data type. It is similar to a column in a table .

data=[1,2,3,4,5]
series=pd.Series(data)
print("series \n",series)
print(type(series))

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
## create  a series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [7]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [9]:
##dataframe
##create a dataframe from a dictionary of list 
data={
    'Name':['Krish','John','Jack'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida
<class 'pandas.core.frame.DataFrame'>

In [10]:
import  numpy as np
np.array(df)

array([['Krish', 25, 'Bangalore'],
       ['John', 30, 'New York'],
       ['Jack', 45, 'Florida']], dtype=object)

In [12]:
## create a dataframe from a list of dictionary
data=[
    {'name':'Krish','age':32,'city':'bangalore'},
     {'name':'Krish','age':32,'city':'bangalore'},
      {'name':'Krish','age':32,'city':'bangalore'},
       {'name':'Krish','age':32,'city':'bangalore'},
]
df=pd.DataFrame(data)
print(df)
print(type(df))

    name  age       city
0  Krish   32  bangalore
1  Krish   32  bangalore
2  Krish   32  bangalore
3  Krish   32  bangalore
<class 'pandas.core.frame.DataFrame'>

In [17]:
df=pd.read_csv('Details.csv')
df.head(5)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card

In [18]:
df.tail(5)

     Order ID  Amount  Profit  Quantity     Category Sub-Category PaymentMode
1495  B-25700       7      -3         2     Clothing  Hankerchief         COD
1496  B-25757    3151     -35         7     Clothing     Trousers         EMI
1497  B-25973    4141    1698        13  Electronics     Printers         COD
1498  B-25698       7      -2         1     Clothing  Hankerchief         COD
1499  B-25993    4363     305         5    Furniture       Tables         EMI

In [23]:
### accessing data from dataframe
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card
...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI
1497,B-25973,4141,1698,13,Electronics,Printers,COD
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4363,305,5,Furniture,Tables,EMI

In [28]:
df['Amount']

0       1096
1       5729
2       2927
3       2847
4       2617
        ...
1495       7
1496    3151
1497    4141
1498       7
1499    4363
Name: Amount, Length: 1500, dtype: int64

In [31]:
df.loc[0][0]

C:\Users\Himanshu Sharma\AppData\Local\Temp\ipykernel_3680\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'B-25681'

In [32]:
 df.iloc[0][0]

C:\Users\Himanshu Sharma\AppData\Local\Temp\ipykernel_3680\1010919896.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'B-25681'

In [36]:
## accessing a specified element 
df.at[2,'Amount']

np.int64(2927)

In [37]:
##   Accesing s specified element 
df.at[2,'Profit']

np.int64(146)

In [38]:
##Accessing a specified element using  iat
df.iat[2,2]

np.int64(146)

In [39]:
### Data Manipulation with Dataframe 
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card
...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI
1497,B-25973,4141,1698,13,Electronics,Printers,COD
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4363,305,5,Furniture,Tables,EMI

In [54]:
##Addding a column
df['Salary'] = 50000
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Salary
0,B-25681,1096,658,7,Electronics,Electronic Games,COD,50000
1,B-26055,5729,64,14,Furniture,Chairs,EMI,50000
2,B-25955,2927,146,8,Furniture,Bookcases,EMI,50000
3,B-26093,2847,712,8,Electronics,Printers,Credit Card,50000
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card,50000
...,...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD,50000
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI,50000
1497,B-25973,4141,1698,13,Electronics,Printers,COD,50000
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD,50000
1499,B-25993,4363,305,5,Furniture,Tables,EMI,50000

In [57]:
## Remove a column 
df.drop('Salary' ,axis=1,inplace=True)## drop does not change original data

In [56]:
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Salary
0,B-25681,1096,658,7,Electronics,Electronic Games,COD,50000
1,B-26055,5729,64,14,Furniture,Chairs,EMI,50000
2,B-25955,2927,146,8,Furniture,Bookcases,EMI,50000
3,B-26093,2847,712,8,Electronics,Printers,Credit Card,50000
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card,50000
...,...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD,50000
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI,50000
1497,B-25973,4141,1698,13,Electronics,Printers,COD,50000
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD,50000
1499,B-25993,4363,305,5,Furniture,Tables,EMI,50000

In [58]:
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card
...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3151,-35,7,Clothing,Trousers,EMI
1497,B-25973,4141,1698,13,Electronics,Printers,COD
1498,B-25698,7,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4363,305,5,Furniture,Tables,EMI

In [60]:
##Add  amount to the column 
df['Amount']=df['Amount']+1
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1097,658,7,Electronics,Electronic Games,COD
1,B-26055,5730,64,14,Furniture,Chairs,EMI
2,B-25955,2928,146,8,Furniture,Bookcases,EMI
3,B-26093,2848,712,8,Electronics,Printers,Credit Card
4,B-25602,2618,1151,4,Electronics,Phones,Credit Card
...,...,...,...,...,...,...,...
1495,B-25700,8,-3,2,Clothing,Hankerchief,COD
1496,B-25757,3152,-35,7,Clothing,Trousers,EMI
1497,B-25973,4142,1698,13,Electronics,Printers,COD
1498,B-25698,8,-2,1,Clothing,Hankerchief,COD
1499,B-25993,4364,305,5,Furniture,Tables,EMI

In [61]:
df.drop(0,inplace=True)

In [62]:
df

     Order ID  Amount  Profit  Quantity     Category Sub-Category  PaymentMode
1     B-26055    5730      64        14    Furniture       Chairs          EMI
2     B-25955    2928     146         8    Furniture    Bookcases          EMI
3     B-26093    2848     712         8  Electronics     Printers  Credit Card
4     B-25602    2618    1151         4  Electronics       Phones  Credit Card
5     B-25881    2245     247         4     Clothing     Trousers  Credit Card
...       ...     ...     ...       ...          ...          ...          ...
1495  B-25700       8      -3         2     Clothing  Hankerchief          COD
1496  B-25757    3152     -35         7     Clothing     Trousers          EMI
1497  B-25973    4142    1698        13  Electronics     Printers          COD
1498  B-25698       8      -2         1     Clothing  Hankerchief          COD
1499  B-25993    4364     305         5    Furniture       Tables          EMI

[1499 rows x 7 columns]

In [63]:
#Display the data types of each column 
print("Data types: \n", df.dtypes)

#Describe the DataFrame
print("Statistical summary:\n",df.describe())

Data types:
 Order ID        object
Amount           int64
Profit           int64
Quantity         int64
Category        object
Sub-Category    object
PaymentMode     object
dtype: object
Statistical summary:
             Amount       Profit     Quantity
count  1499.000000  1499.000000  1499.000000
mean    292.310874    24.219480     3.741161
std     461.611117   167.818579     2.184050
min       5.000000 -1981.000000     1.000000
25%      48.500000   -12.000000     2.000000
50%     123.000000     8.000000     3.000000
75%     326.500000    38.000000     5.000000
max    5730.000000  1864.000000    14.000000

In [64]:
df.describe()

            Amount       Profit     Quantity
count  1499.000000  1499.000000  1499.000000
mean    292.310874    24.219480     3.741161
std     461.611117   167.818579     2.184050
min       5.000000 -1981.000000     1.000000
25%      48.500000   -12.000000     2.000000
50%     123.000000     8.000000     3.000000
75%     326.500000    38.000000     5.000000
max    5730.000000  1864.000000    14.000000